# See https://github.com/jucrouzet/docker-go-alpine-gometalinter
FROM jcrouzet/docker-go-alpine-gometalinter:latest as buildEnvironment

# The base image avoid the following step (RUN) to be run each time (no cache)
#RUN                     \
#    apk add --update    \
#        binutils        \
#        git             \
#        make

